[FIX] _change_generic: Avoid error when changing mail.followers
If you have following situation:

- Target record with no followers.
- Record to merge 1 with follower 1.
- Record to merge 2 with follower 1.

When executing the merge and changing followers references, you get the
following error:

IntegrityError: duplicate key value violates unique constraint "mail_followers_mail_followers_res_partner_res_model_id_uniq"
DETAIL:  Key (res_model, res_id, partner_id)=(..., ..., 1) already exists

And it's because both followers are changed to the target record. For
avoiding this problem, we serialize the changes, so that for the second
record to merge, no update is performed.